# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:            arkane0906
tagline:          Manuals, Tricks and Advices for Web
description:      'Привет, друзья! Меня зовут Идельбаев Евгений и это мой блог. Здесь я пишу о веб-разработке и программировании. Надеюсь, буду полезен!'
url:              http://arkane0906.github.io/arkane0906.github.io

author:
  name:              Eugen Idelbaev
  url:               https://vk.com/idelbaev

paginate:         3

# Custom vars
version:          2.0.1

github:
  repo:           https://github.com/arkane0906/arkane0906.github.io
