# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Arkane
tagline:             Заметки программиста
url:                 http://arkane0906.github.io/jekyll-blog
paginate:            1
baseurl:             "/jekyll-blog"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Eugen Idelbaev
  url:               https://vk.com/idelbaev
  email:             arkane0906@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/arkane0906/jekyll-blog

# Top links
pages_list:
  О блоге: '/jekyll-blog/about'
  Архив записей: '/jekyll-blog/archive'
  Лента: '/jekyll-blog/atom.xml'
